const { test, expect } = require("@playwright/test");

const waypointsTextOnePoint = `[
  { "lat": 36.85, "lon": -76.30, "eta": "2026-07-09T12:00:00Z" }
]`;

const largeWaypointCount = 50;
const sixHoursMs = 6 * 60 * 60 * 1000;
const SUMMARY_GENERATING_TEXT = "... Generating";
const WEATHER_SITUATION_RESPONSE_TIMEOUT_MS = 15000;
const MOCK_SUMMARY_SENTINEL = "Generated by Playwright summary mock.";
const REAL_GEMINI_TEST_TAG = "[real-gemini]";

function createRandomWaypoints(count = largeWaypointCount) {
  const firstEtaMs = Date.parse("2026-07-09T12:00:00Z");

  return Array.from({ length: count }, (_, index) => ({
    lat: Number((Math.random() * 170 - 85).toFixed(4)),
    lon: Number((Math.random() * 350 - 175).toFixed(4)),
    eta: new Date(firstEtaMs + index * sixHoursMs)
      .toISOString()
      .replace(".000Z", "Z")
  }));
}

const waypointsTextOversize = `[
    { "lat": 68.10, "lon": -145.76, "eta": "2026-07-09T06:00:00Z" },
    { "lat": 64.84, "lon": -147.72, "eta": "2026-07-09T12:00:00Z" },
    { "lat": 61.58, "lon": -149.68, "eta": "2026-07-09T18:00:00Z" },
    { "lat": 60.50, "lon": -144.00, "eta": "2026-07-10T00:00:00Z" },
    { "lat": 59.70, "lon": -137.37, "eta": "2026-07-10T06:00:00Z" },
    { "lat": 59.68, "lon": -134.78, "eta": "2026-07-10T12:00:00Z" },
    { "lat": 57.19, "lon": -131.46, "eta": "2026-07-10T18:00:00Z" },
    { "lat": 55.30, "lon": -126.43, "eta": "2026-07-11T00:00:00Z" },
    { "lat": 53.02, "lon": -122.82, "eta": "2026-07-11T06:00:00Z" },
    { "lat": 49.64, "lon": -123.09, "eta": "2026-07-11T12:00:00Z" },
    { "lat": 46.35, "lon": -122.54, "eta": "2026-07-11T18:00:00Z" },
    { "lat": 42.98, "lon": -122.53, "eta": "2026-07-12T00:00:00Z" },
    { "lat": 39.60, "lon": -122.40, "eta": "2026-07-12T06:00:00Z" },
    { "lat": 36.63, "lon": -121.14, "eta": "2026-07-12T12:00:00Z" },
    { "lat": 34.13, "lon": -118.33, "eta": "2026-07-12T18:00:00Z" },
    { "lat": 31.78, "lon": -115.55, "eta": "2026-07-13T00:00:00Z" },
    { "lat": 29.89, "lon": -112.30, "eta": "2026-07-13T06:00:00Z" },
    { "lat": 28.43, "lon": -108.85, "eta": "2026-07-13T12:00:00Z" },
    { "lat": 27.28, "lon": -105.27, "eta": "2026-07-13T18:00:00Z" },
    { "lat": 26.13, "lon": -101.69, "eta": "2026-07-14T00:00:00Z" },
    { "lat": 23.87, "lon": -101.42, "eta": "2026-07-14T06:00:00Z" },
    { "lat": 20.91, "lon": -103.20, "eta": "2026-07-14T12:00:00Z" },
    { "lat": 19.74, "lon": -100.20, "eta": "2026-07-14T18:00:00Z" },
    { "lat": 18.44, "lon": -96.91, "eta": "2026-07-15T00:00:00Z" },
    { "lat": 17.01, "lon": -93.70, "eta": "2026-07-15T06:00:00Z" },
    { "lat": 14.96, "lon": -90.92, "eta": "2026-07-15T12:00:00Z" },
    { "lat": 13.07, "lon": -88.04, "eta": "2026-07-15T18:00:00Z" },
    { "lat": 11.12, "lon": -85.26, "eta": "2026-07-16T00:00:00Z" },
    { "lat": 9.58, "lon": -82.38, "eta": "2026-07-16T06:00:00Z" },
    { "lat": 8.70, "lon": -79.11, "eta": "2026-07-16T12:00:00Z" },
    { "lat": 6.77, "lon": -76.31, "eta": "2026-07-16T18:00:00Z" },
    { "lat": 4.46, "lon": -74.30, "eta": "2026-07-17T00:00:00Z" },
    { "lat": 1.97, "lon": -76.58, "eta": "2026-07-17T06:00:00Z" },
    { "lat": -0.69, "lon": -78.57, "eta": "2026-07-17T12:00:00Z" },
    { "lat": -4.02, "lon": -79.01, "eta": "2026-07-17T18:00:00Z" },
    { "lat": -7.40, "lon": -79.03, "eta": "2026-07-18T00:00:00Z" },
    { "lat": -10.50, "lon": -77.82, "eta": "2026-07-18T06:00:00Z" },
    { "lat": -13.09, "lon": -75.72, "eta": "2026-07-18T12:00:00Z" },
    { "lat": -15.23, "lon": -73.02, "eta": "2026-07-18T18:00:00Z" },
    { "lat": -17.61, "lon": -70.57, "eta": "2026-07-19T00:00:00Z" },
    { "lat": -20.89, "lon": -70.33, "eta": "2026-07-19T06:00:00Z" },
    { "lat": -24.26, "lon": -70.48, "eta": "2026-07-19T12:00:00Z" },
    { "lat": -27.62, "lon": -70.94, "eta": "2026-07-19T18:00:00Z" },
    { "lat": -30.97, "lon": -71.07, "eta": "2026-07-20T00:00:00Z" },
    { "lat": -34.20, "lon": -71.19, "eta": "2026-07-20T06:00:00Z" },
    { "lat": -37.17, "lon": -73.04, "eta": "2026-07-20T12:00:00Z" },
    { "lat": -40.55, "lon": -72.96, "eta": "2026-07-20T18:00:00Z" },
    { "lat": -43.90, "lon": -72.42, "eta": "2026-07-21T00:00:00Z" },
    { "lat": -47.26, "lon": -72.19, "eta": "2026-07-21T06:00:00Z" },
    { "lat": -50.64, "lon": -72.42, "eta": "2026-07-21T12:00:00Z" },
    { "lat": -54.80, "lon": -68.30, "eta": "2026-07-21T21:00:00Z" },
    { "lat": -58.96, "lon": -64.18, "eta": "2026-07-22T03:00:00Z" }
]`;

const largeForecastBrowserWaitMs = 0;

function normalizeSummaryMode(summaryMode) {
  return summaryMode === "deterministic" ? "deterministic" : "gemini";
}

function parseFiniteNumber(value) {
  if (value === null || value === undefined || value === "") {
    return null;
  }

  const number = Number(value);
  return Number.isFinite(number) ? number : null;
}

function formatSummaryNumber(value, digits) {
  const number = parseFiniteNumber(value);
  return number === null ? "unavailable" : number.toFixed(digits);
}

function formatSummaryDirection(value) {
  const number = parseFiniteNumber(value);
  return number === null ? "unavailable" : `${number.toFixed(0)}°`;
}

function buildMockSummaryResponse(requestBody) {
  const summaryMode = normalizeSummaryMode(requestBody?.summary_mode);
  const route = Array.isArray(requestBody?.route) ? requestBody.route : [];
  const firstWaypoint = route[0] ?? {};
  const generatorLabel = summaryMode === "gemini" ? "Gemini" : "Deterministic";
  const vehicleName = requestBody?.vehicle_name || "Unknown vehicle";
  const routeName = requestBody?.route_name || "Unknown route";

  return {
    route,
    summary:
      `${MOCK_SUMMARY_SENTINEL} ${generatorLabel} mock summary for ${vehicleName} on ${routeName}. `
      + `${route.length} waypoint(s). WP-1 temp ${formatSummaryNumber(firstWaypoint.temperature_f, 1)} F, `
      + `wind ${formatSummaryNumber(firstWaypoint.wind_speed_knots, 1)} knots, `
      + `direction ${formatSummaryDirection(firstWaypoint.wind_direction_deg)}, `
      + `humidity ${formatSummaryNumber(firstWaypoint.humidity_pct, 0)}%, `
      + `precipitation ${formatSummaryNumber(firstWaypoint.precipitation_in, 2)} in.`,
    summary_mode: summaryMode,
    validation: []
  };
}

async function installMockSummaryRoute(page) {
  await page.route("**/api/v1/summary", async (route) => {
    const requestBody = route.request().postDataJSON();
    const mockResponse = buildMockSummaryResponse(requestBody);

    await route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify(mockResponse)
    });
  });
}

function waitForSummaryResponse(page) {
  return page.waitForResponse(
    (response) => (
      response.url().includes("/api/v1/summary")
      && response.request().method() === "POST"
    ),
    { timeout: WEATHER_SITUATION_RESPONSE_TIMEOUT_MS }
  );
}

async function waitForWeatherSituationReady(page) {
  const weatherSituation = page.getByLabel("Weather Situation");

  await expect(weatherSituation).toBeVisible();
  await expect(weatherSituation).not.toHaveValue(SUMMARY_GENERATING_TEXT, {
    timeout: WEATHER_SITUATION_RESPONSE_TIMEOUT_MS
  });

  return weatherSituation;
}

test.beforeEach(async ({ page }, testInfo) => {
  if (testInfo.title.includes(REAL_GEMINI_TEST_TAG)) {
    return;
  }

  await installMockSummaryRoute(page);
});

test.afterEach(async ({ page }, testInfo) => {
  if (testInfo.title.includes("Large forecast test") && !page.isClosed()) {
    await page.waitForTimeout(largeForecastBrowserWaitMs);
  }
});

async function openAndRunForecast(page, waypoints = waypointsTextOnePoint) {
  await page.goto("/");

  await page.locator("textarea").first().fill(waypoints);
  const forecastResponsePromise = page.waitForResponse((response) => {
    return (
      response.url().includes("/api/v1/forecast") &&
      response.request().method() === "POST"
    );
  });
  const summaryResponsePromise = waitForSummaryResponse(page).catch(() => null);

  await page.getByRole("button", { name: /run forecast/i }).click();
  const forecastResponse = await forecastResponsePromise;
  let summaryResponse = null;

  if (forecastResponse.ok()) {
    summaryResponse = await summaryResponsePromise;
    expect(summaryResponse, "Weather Situation summary response was not observed.").not.toBeNull();
    expect(summaryResponse.ok()).toBe(true);
    await waitForWeatherSituationReady(page);
  }

  return { forecastResponse, summaryResponse };
}

async function assertPeakValuesAndTravelDetails(page, waypointCount) {
  const peakValues = page.locator(".peak-card .peak-value");

  await expect(peakValues).toHaveCount(4);
  for (let index = 0; index < 4; index++) {
    await expect(peakValues.nth(index)).not.toHaveText("");
    await expect(peakValues.nth(index)).not.toHaveText("N/A");
  }

  const travelRows = page.locator(".travel-card tbody tr");
  const travelTime = travelRows.nth(0).locator("td").nth(1);
  const travelDistance = travelRows.nth(1).locator("td").nth(1);

  await expect(travelRows).toHaveCount(2);
  await expect(travelTime).not.toHaveText("");
  await expect(travelDistance).not.toHaveText("");

  if (waypointCount < 2) {
    await expect(travelTime).toHaveText("N/A");
    await expect(travelDistance).toHaveText("N/A");
    return;
  }

  await expect(travelTime).toContainText(/hrs/);
  await expect(travelDistance).toContainText(/mi/);
}

async function assertWeatherInputsHaveNumbers(rows, rowCount) {
  const fieldNames = ["Temp °F", "Wind Knots", "Wind Dir °", "Humidity %", "Precipitation"];

  for (let rowIndex = 0; rowIndex < rowCount; rowIndex++) {
    const weatherInputs = rows.nth(rowIndex).locator('input[type="number"]');

    await expect(weatherInputs).toHaveCount(fieldNames.length);

    for (let fieldIndex = 0; fieldIndex < fieldNames.length; fieldIndex++) {
      const input = weatherInputs.nth(fieldIndex);
      const value = await input.inputValue();
      const fieldName = fieldNames[fieldIndex];
      const waypointNumber = rowIndex + 1;

      expect(value, `${fieldName} is blank for WP-${waypointNumber}`).not.toBe("");
      expect(
        Number.isFinite(Number(value)),
        `${fieldName} must be numeric for WP-${waypointNumber}; got "${value}"`
      ).toBe(true);
    }
  }
}

async function assertWeatherInputsMatchValues(row, expectedValues) {
  const weatherInputs = row.locator('input[type="number"]');
  const expectedInputValues = [
    expectedValues.temperature_f,
    expectedValues.wind_speed_knots,
    expectedValues.wind_direction_deg,
    expectedValues.humidity_pct,
    expectedValues.precipitation_in
  ];

  await expect(weatherInputs).toHaveCount(expectedInputValues.length);

  for (let index = 0; index < expectedInputValues.length; index++) {
    const expectedValue = expectedInputValues[index];
    if (expectedValue instanceof RegExp) {
      await expect(weatherInputs.nth(index)).toHaveValue(expectedValue);
      continue;
    }

    await expect(weatherInputs.nth(index)).toHaveValue(String(expectedValue));
  }
}

async function assertWaypointEndpoints(rows, waypoints) {
  const firstWaypoint = waypoints[0];
  const lastWaypoint = waypoints[waypoints.length - 1];

  await expect(rows.first().locator(".waypoint-name-cell span")).toHaveText("1");
  await expect(rows.first().locator("td").nth(1)).toHaveText(firstWaypoint.eta);
  await expect(rows.first().locator("td").nth(2)).toHaveText(String(firstWaypoint.lat));
  await expect(rows.first().locator("td").nth(3)).toHaveText(String(firstWaypoint.lon));

  await expect(rows.last().locator(".waypoint-name-cell span")).toHaveText(String(waypoints.length));
  await expect(rows.last().locator("td").nth(1)).toHaveText(lastWaypoint.eta);
  await expect(rows.last().locator("td").nth(2)).toHaveText(String(lastWaypoint.lat));
  await expect(rows.last().locator("td").nth(3)).toHaveText(String(lastWaypoint.lon));
}


// 1 waypoint (validate weather information)
test("Small forecast test with data validation", async ({ page }) => {
  const smallWaypoints = JSON.parse(waypointsTextOnePoint);
  const expectedWeather = {
    ...smallWaypoints[0],
    temperature_f: 77,
    wind_speed_knots: 2.8, // updated from mph and confirmed value
    wind_direction_deg: 146,
    humidity_pct: 90,
    precipitation_in: 0
  };

  await openAndRunForecast(page);

  const weatherTable = page
    .locator("table")
    .filter({ hasText: "Temp °F" })
    .first();
  const rows = weatherTable.locator("tbody tr");

  await expect(rows).toHaveCount(smallWaypoints.length);

  await assertWeatherInputsHaveNumbers(rows, smallWaypoints.length);
  await assertWeatherInputsMatchValues(rows.first(), expectedWeather);
  await assertWaypointEndpoints(rows, smallWaypoints);

  await assertPeakValuesAndTravelDetails(page, smallWaypoints.length);
});

test("Wind barb feathers angle outward from the staff", async ({ page }) => {
  await openAndRunForecast(page);

  const firstFeather = page.locator(".wind-map-waypoint-barb-feather").first();
  await expect(firstFeather).toBeVisible();

  const y1 = Number(await firstFeather.getAttribute("y1"));
  const y2 = Number(await firstFeather.getAttribute("y2"));

  expect(Number.isFinite(y1)).toBe(true);
  expect(Number.isFinite(y2)).toBe(true);
  expect(y2).toBeLessThan(y1);
});

test("Weather Situation shows the current summary type", async ({ page }) => {
  await openAndRunForecast(page);

  const weatherSituationCard = page.locator(".card").filter({ hasText: "Weather Situation" }).first();
  const weatherSituation = await waitForWeatherSituationReady(page);

  await expect(weatherSituation).toHaveValue(new RegExp(MOCK_SUMMARY_SENTINEL));
  await expect(weatherSituationCard).toContainText("Gemini Summary");

  const summaryResponsePromise = waitForSummaryResponse(page);
  await page
    .getByRole("button", { name: /regenerate\s*gemini summary/i })
    .first().click();

  const summaryResponse = await summaryResponsePromise;
  expect(summaryResponse.ok()).toBe(true);

  await waitForWeatherSituationReady(page);
  await expect(weatherSituationCard).toContainText("Gemini Summary");
  await expect(weatherSituationCard).toContainText(
    "Weather Situation regenerated using Gemini."
  );
});

test(`${REAL_GEMINI_TEST_TAG} Gemini summary generation uses the live AI response`, async ({ page }) => {
  const { summaryResponse } = await openAndRunForecast(page);
  const weatherSituationCard = page.locator(".card").filter({ hasText: "Weather Situation" }).first();
  const weatherSituation = await waitForWeatherSituationReady(page);

  expect(summaryResponse, "Expected the live Gemini summary response.").not.toBeNull();

  const summaryData = await summaryResponse.json();
  const summaryWarnings = (summaryData.validation ?? [])
    .map((finding) => finding?.message)
    .filter(Boolean);

  expect(
    summaryData.summary_mode,
    `Expected Gemini to generate the Weather Situation, but the backend returned `
    + `"${summaryData.summary_mode}". ${summaryWarnings.join(" ")}`
  ).toBe("gemini");
  expect(typeof summaryData.summary).toBe("string");
  expect(summaryData.summary.trim().length).toBeGreaterThan(0);
  expect(summaryData.summary).not.toContain(MOCK_SUMMARY_SENTINEL);

  await expect(weatherSituation).toHaveValue(summaryData.summary);
  await expect(weatherSituationCard).toContainText("Gemini Summary");
  await expect(weatherSituationCard).toContainText("Weather Situation generated using Gemini.");
});

test("Wind barb pennants and feathers have visible spacing between them", async ({ page }) => {
  await openAndRunForecast(page);

  const weatherTable = page
    .locator("table")
    .filter({ hasText: "Temp °F" })
    .first();
  const firstRowInputs = weatherTable.locator("tbody tr").first().locator('input[type="number"]');

  await firstRowInputs.nth(1).fill("65");

  const firstMarker = page.locator('[data-waypoint-number="1"]').first();
  const firstPennant = firstMarker.locator(".wind-map-waypoint-barb-pennant").first();
  const feathers = firstMarker.locator(".wind-map-waypoint-barb-feather");
  const firstFeather = feathers.first();
  const secondFeather = feathers.nth(1);

  await expect(firstPennant).toBeVisible();
  await expect(firstFeather).toBeVisible();
  await expect(secondFeather).toBeVisible();

  const points = (await firstPennant.getAttribute("points")) ?? "";
  const pennantBottomY = Math.max(
    ...points
      .trim()
      .split(/\s+/)
      .map((pair) => Number(pair.split(",")[1]))
  );
  const firstFeatherY1 = Number(await firstFeather.getAttribute("y1"));
  const secondFeatherY1 = Number(await secondFeather.getAttribute("y1"));
  const pennantToFirstFeatherGap = firstFeatherY1 - pennantBottomY;
  const featherToFeatherGap = secondFeatherY1 - firstFeatherY1;

  expect(Number.isFinite(pennantBottomY)).toBe(true);
  expect(Number.isFinite(firstFeatherY1)).toBe(true);
  expect(Number.isFinite(secondFeatherY1)).toBe(true);
  expect(pennantToFirstFeatherGap).toBe(featherToFeatherGap);
});

test("Valid wind direction with zero wind speed shows only the warning waypoint", async ({ page }) => {
  await openAndRunForecast(page);

  const weatherTable = page
    .locator("table")
    .filter({ hasText: "Temp °F" })
    .first();
  const firstRowInputs = weatherTable.locator("tbody tr").first().locator('input[type="number"]');

  await firstRowInputs.nth(2).fill("45");
  await firstRowInputs.nth(1).fill("0");

  const firstMarker = page.locator('[data-waypoint-number="1"]').first();

  await expect(firstMarker).toHaveAttribute("data-marker-state", "speed-warning");
  await expect(firstMarker.locator(".wind-map-waypoint-barb-staff")).toHaveCount(0);
  await expect(firstMarker.locator(".wind-map-waypoint-barb-feather")).toHaveCount(0);
  await expect(firstMarker.locator(".wind-map-waypoint-hit-area")).toHaveAttribute(
    "title",
    /speed unavailable/i
  );
});

test("Zero wind speed with zero wind direction keeps the normal waypoint color", async ({ page }) => {
  await openAndRunForecast(page);

  const weatherTable = page
    .locator("table")
    .filter({ hasText: "Temp °F" })
    .first();
  const firstRowInputs = weatherTable.locator("tbody tr").first().locator('input[type="number"]');

  await firstRowInputs.nth(2).fill("0");
  await firstRowInputs.nth(1).fill("0");

  const firstMarker = page.locator('[data-waypoint-number="1"]').first();
  const firstMarkerCircle = firstMarker.locator(".wind-map-waypoint-circle-shape");

  await expect(firstMarker).toHaveAttribute("data-marker-state", "circle-only");
  await expect(firstMarkerCircle).toBeVisible();
  await expect(firstMarkerCircle).toHaveCSS("fill", "rgb(30, 139, 195)");
  await expect(firstMarker.locator(".wind-map-waypoint-barb-staff")).toHaveCount(0);
  await expect(firstMarker.locator(".wind-map-waypoint-barb-feather")).toHaveCount(0);
  await expect(firstMarker.locator(".wind-map-waypoint-barb-pennant")).toHaveCount(0);
});

test("Nonzero wind speed with zero wind direction uses the warning waypoint look", async ({ page }) => {
  await openAndRunForecast(page);

  const weatherTable = page
    .locator("table")
    .filter({ hasText: "Temp °F" })
    .first();
  const firstRowInputs = weatherTable.locator("tbody tr").first().locator('input[type="number"]');

  await firstRowInputs.nth(2).fill("0");
  await firstRowInputs.nth(1).fill("12");

  const firstMarker = page.locator('[data-waypoint-number="1"]').first();
  const firstMarkerCircle = firstMarker.locator(".wind-map-waypoint-circle-shape");

  await expect(firstMarker).toHaveAttribute("data-marker-state", "direction-warning");
  await expect(firstMarkerCircle).toBeVisible();
  await expect(firstMarkerCircle).toHaveCSS("fill", "rgb(239, 83, 80)");
  await expect(firstMarker.locator(".wind-map-waypoint-barb-staff")).toHaveCount(0);
  await expect(firstMarker.locator(".wind-map-waypoint-barb-feather")).toHaveCount(0);
  await expect(firstMarker.locator(".wind-map-waypoint-barb-pennant")).toHaveCount(0);
  await expect(firstMarker.locator(".wind-map-waypoint-hit-area")).toHaveAttribute(
    "title",
    /wind direction unavailable/i
  );
});

test("Nonzero wind speed with blank wind direction uses the warning waypoint look", async ({ page }) => {
  await openAndRunForecast(page);

  const weatherTable = page
    .locator("table")
    .filter({ hasText: "Temp °F" })
    .first();
  const firstRowInputs = weatherTable.locator("tbody tr").first().locator('input[type="number"]');

  await firstRowInputs.nth(2).fill("");
  await firstRowInputs.nth(1).fill("12");

  const firstMarker = page.locator('[data-waypoint-number="1"]').first();
  const firstMarkerCircle = firstMarker.locator(".wind-map-waypoint-circle-shape");

  await expect(firstMarker).toHaveAttribute("data-marker-state", "direction-warning");
  await expect(firstMarkerCircle).toBeVisible();
  await expect(firstMarkerCircle).toHaveCSS("fill", "rgb(239, 83, 80)");
  await expect(firstMarker.locator(".wind-map-waypoint-barb-staff")).toHaveCount(0);
  await expect(firstMarker.locator(".wind-map-waypoint-barb-feather")).toHaveCount(0);
  await expect(firstMarker.locator(".wind-map-waypoint-barb-pennant")).toHaveCount(0);
  await expect(firstMarker.locator(".wind-map-waypoint-hit-area")).toHaveAttribute(
    "title",
    /wind direction unavailable/i
  );
});

// 5 waypoints (Default) (confirm no errors)
test("Prefilled waypoints test", async ({ page }) => {
  await page.goto("/");

  const prefilledWaypointsText = await page.locator("textarea").first().inputValue();
  const prefilledWaypoints = JSON.parse(prefilledWaypointsText);

  await openAndRunForecast(page, prefilledWaypointsText);

  const weatherTable = page
    .locator("table")
    .filter({ hasText: "Temp °F" })
    .first();
  const rows = weatherTable.locator("tbody tr");

  await expect(rows).toHaveCount(prefilledWaypoints.length);

  await assertWeatherInputsHaveNumbers(rows, prefilledWaypoints.length);
  await assertWaypointEndpoints(rows, prefilledWaypoints);

  await assertPeakValuesAndTravelDetails(page, prefilledWaypoints.length);
});

// 50 waypoints (confirm no missing values)
test("Large forecast test", async ({ page }, testInfo) => {
  testInfo.setTimeout(largeForecastBrowserWaitMs + 120000);

  const largeWaypoints = createRandomWaypoints();

  await openAndRunForecast(page, JSON.stringify(largeWaypoints));

  const weatherTable = page
    .locator("table")
    .filter({ hasText: "Temp °F" })
    .first();
  const rows = weatherTable.locator("tbody tr");

  await expect(rows).toHaveCount(largeWaypoints.length);

  await assertWeatherInputsHaveNumbers(rows, largeWaypoints.length);
  await assertWaypointEndpoints(rows, largeWaypoints);

  await assertPeakValuesAndTravelDetails(page, largeWaypoints.length);
});

// 52 waypoints (confirm validation error)
test("Oversize forecast test", async ({ page }) => {
  await openAndRunForecast(page, waypointsTextOversize);

  await expect(
    page.getByText("List should have at most 50 items after validation, not 52", {
      exact: true
    })
  ).toBeVisible();
});

// Run forecast, update data and regenerate Weather Situation
test("Edit data test", async ({ page }) => {
  await openAndRunForecast(page);

  const vehicleName = "Edit Test Vessel";
  const routeName = "Edit Test Route";
  const nameInputs = page.locator('input[type="text"]');

  await nameInputs.nth(0).fill(vehicleName);
  await nameInputs.nth(1).fill(routeName);

  const weatherTable = page
    .locator("table")
    .filter({ hasText: "Temp °F" })
    .first();
  const rows = weatherTable.locator("tbody tr");

  const weatherSituation = page.getByLabel("Weather Situation");
  await expect(weatherSituation).toBeVisible();
  const oldWeatherSituation = await weatherSituation.inputValue();
  const editedWeatherValues = [1, 1, 45, 1, 1];
  const weatherInputs = rows.first().locator('input[type="number"]');

  for (let index = 0; index < editedWeatherValues.length; index++) {
    await weatherInputs.nth(index).fill(String(editedWeatherValues[index]));
  }

  await expect(weatherInputs).toHaveCount(editedWeatherValues.length);
  await expect(page.locator(".peak-card .peak-value")).toHaveText([
    "1",
    "1",
    "1",
    "1"
  ]);

  const summaryResponsePromise = waitForSummaryResponse(page);
  await page
    .getByRole("button", { name: /regenerate\s*deterministic summary/i })
    .first().click();

  const summaryResponse = await summaryResponsePromise;
  expect(summaryResponse.ok()).toBe(true);

  await waitForWeatherSituationReady(page);
  await expect(weatherSituation).not.toHaveValue(oldWeatherSituation);
  await expect(weatherSituation).toHaveValue(new RegExp(MOCK_SUMMARY_SENTINEL));
  await expect(weatherSituation).toHaveValue(new RegExp(vehicleName));
  await expect(weatherSituation).toHaveValue(new RegExp(routeName));
  await expect(weatherSituation).toHaveValue(/temp 1\.0 F/i);
  await expect(weatherSituation).toHaveValue(/wind 1\.0 knots/i);
  await expect(weatherSituation).toHaveValue(/direction 45°/i);
  await expect(weatherSituation).toHaveValue(/humidity 1%/i);
  await expect(weatherSituation).toHaveValue(/precipitation 1\.00 in/i);
});
